### ISSUE TITLE
Upgrade to SPFx 1.4?

### ISSUE THREAD

**Issue by aaronmi** [thechriskent/ColumnFormatter#1]
I love the tool! 
It'd greatly easy the deployment if it could be upgraded to SPFx 1.4.

**Comment by schneika** [comment]
I am also not able to "gulp build --ship" the solution with a CDN or with the new SPFx 1.4 asset packaging.

**Comment by thechriskent** [comment]
Totally agree! There are some additional updates (including this suggestion) that will be included in an upcoming addition to the official SharePoint PnP repositories. This should be done this week and I'll update this issue once it's available. Thanks!

**Comment by weronika2505199** [comment]
Are you going to update it?  It still does not work with "gulp build --ship".

**Comment by thechriskent** [comment]
My apologies! Yes, this project was integrated with SharePoint Patterns & Practices and was moved there:
https://github.com/SharePoint/sp-dev-solutions/tree/master/solutions/ColumnFormatter

There are several updates including support for 1.4 with Asset Bundling. The bundle takes a long time to build so I've included the [bundled app package](https://github.com/SharePoint/sp-dev-solutions/raw/master/solutions/ColumnFormatter/assets/column-formatter.sppkg). Additional details about using and installing this webpart in your tenant are also available:
https://github.com/SharePoint/sp-dev-solutions/blob/master/solutions/ColumnFormatter/docs/documentation/docs/index.md

I am closing this issue for now and will update the readme for this repository to indicate the new location. Please reach out with any other questions or concerns, thanks!

**Comment by weronika2505199** [comment]
It works. Thanks :)
